describe('Automate demo website', () => {
    it('Should automate the demo website', () => {
      cy.visit('https://demo.automationtesting.in/Register.html')
      cy.wait(2000)
      cy.title().should('eq','Register')
      cy.get("input[placeholder='First Name']").type('Kavinkumar')
      cy.get("input[placeholder='Last Name']").type('V')
      cy.get(".form-control.ng-pristine.ng-untouched.ng-valid[rows='3']").type("266, Gobi")
      cy.get("input[type='email']").type('kavinkumarv1996@gmail.com')
      cy.get("input[type='tel']").type('6385667529')
      cy.get("input[value='Male']").check();
      cy.get("#checkbox1").check()
      cy.wait(2000)
      cy.get("#msdd").click()
      cy.get("section[id='section'] li:nth-child(8) a:nth-child(1)").click()
      cy.wait(2000)
      cy.get("#checkbox2").check()
      cy.get("#Skills").select("Java")
      cy.get("span[role='combobox']").click()
      cy.wait(2000)
      cy.get("input[role='textbox']").type('India').type('{enter}')
      cy.get("#yearbox").select("1996")
      cy.get("select[placeholder='Month']").select("July")
      cy.get("#daybox").select("16")
      cy.wait(2000)
      cy.get("#firstpassword").type('test@123')
      cy.get("#secondpassword").type('test@123')
      cy.get('#submitbtn').click();
      cy.get("#Button1").click();
    })
  })