name: Cypress Tests

on:
  push:
    branches:
      - main
      - sub-branch  # Specify the branches where the workflow will run
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # GitHub runner environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Node.js with Cypress
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run

      # Upload test results (optional)
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/reports # Assuming you generate reports

      # Optionally publish test results to GitHub Pages or as artifacts


